### ISSUE TITLE
extend bluetooth coverage to transmit packets?!

### ISSUE THREAD

**Issue by 50494554524F** [myhomeiot/esphome-components#14]
(sorry for the dumb question, i started studying esphome few days ago)

now i can extend the bluetooth coverage to receive data from sensors far away very easily but...

what if i want to send a command form home assistant to a bluetooth bot that is far away too?! is it possible using something similar?!

thanks

**Comment by myhomeiot** [comment]
For sending command to Bluetooth device you should use ESPHome [BLE Client](https://esphome.io/components/ble_client.html) at specific ESPHome device, sure will be better if this device will be close to BT device which you want to control.

As a command trigger from HA you can use any suitable entities like [button](https://esphome.io/components/button/index.html), [switch](https://esphome.io/components/switch/template.html) or even ESPHome [User-defined Services](https://esphome.io/components/api.html#api-homeassistant-service-action).

[Here](https://github.com/myhomeiot/esphome-components/blob/main/examples/ble_client/delonghi.yaml) you can find the example which send commands to Delonghi Coffee machine and expose this to HA as a buttons.

Hope this helps.
