### ISSUE TITLE
Support for Tasmota32 ?

### ISSUE THREAD

**Issue by taylormia** [myhomeiot/esphome-components#18]
I use the Passive BLE Monitor component and have the Switchbot Mini Plug that uses the ESP32-C3 and can be flashed with the [Tasmota32](https://tasmota.github.io/docs/ESP32/) firmware that supports this device. Any chance that the BLE Gateway component will support this firmware?

**Comment by myhomeiot** [comment]
Tasmota32 its different firmware and i think something similar as BLE Gateway can be done for it, but as I can see [here](https://community.home-assistant.io/t/support-for-switchbot-plug-mini-w1901400-with-ble-tracking/441893/5) Switchbot Mini Plug can be flashed with ESPHome with working BLE, so BLE Gateway should work in this case.

Let's me know if it's helps.
